#!/bin/sh
# Copyright 2014 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.


# Redirect output to stderr.
exec 1>&2


run_checks() {
  # Ensure everything is either tracked or ignored. This is because git stash
  # doesn't stash untracked files.
  untracked="$(git ls-files --others --exclude-standard)"
  if [ "$untracked" != "" ]; then
    echo "This check refuses to run if there is an untracked file. Either track"
    echo "it or put it in the .gitignore or your global exclusion list:"
    echo "$untracked"
    return 1
  fi

  # Ensure all .go files are properly formatted.
  gofiles="$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')"
  if [ "$gofiles" != "" ]; then
    # TODO(maruel): Make it work with with whitespaces.
    unformatted=$(gofmt -l $gofiles)
    if [ "$unformatted" != "" ]; then
      echo "Go files must be formatted with gofmt. Please run:"
      for fn in $unformatted; do
        echo "  gofmt -w $PWD/$fn"
      done
      return 1
    fi
  fi

  # If there are whitespace errors, print the offending file names and fail.
  # It's somewhat redundant with the gofmt check above but it also checks
  # non-.go files.
  git diff-index --check --cached $against --
  result=$?
  if [ $result != 0 ]; then
    return $result
  fi

  # Run the presubmit check.
  python presubmit.py
  result=$?
  if [ $result != 0 ]; then
    return $result
  fi
}


if git rev-parse --verify HEAD >/dev/null 2>&1
then
  against=HEAD
else
  # Initial commit: diff against an empty tree object
  against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi


# Use a precise "stash, run checks, unstash" to ensure that the check is
# properly run on the data in the index.
# Inspired from
# http://stackoverflow.com/questions/20479794/how-do-i-properly-git-stash-pop-in-pre-commit-hooks-to-get-a-clean-working-tree
# First, stash index and work dir, keeping only the to-be-committed changes in
# the working directory.
old_stash=$(git rev-parse -q --verify refs/stash)
git stash save -q --keep-index
new_stash=$(git rev-parse -q --verify refs/stash)

# If there were no changes (e.g., `--amend` or `--allow-empty`) then nothing was
# stashed, and we should skip everything, including the tests themselves.
# (Presumably the tests passed on the previous commit, so there is no need to
# re-run them.)
if [ "$old_stash" = "$new_stash" ]; then
  exit 0
fi

run_checks
result=$?

# Restore changes.
git reset --hard -q && git stash apply --index -q && git stash drop -q
exit $result
