// generated by stringer -output=command_string.go -type=CommandCategory; DO NOT EDIT

package wicore

import "fmt"

const _CommandCategory_name = "UnknownCategoryWindowCategoryCommandsCategoryEditorCategoryDebugCategory"

var _CommandCategory_index = [...]uint8{0, 15, 29, 45, 59, 72}

func (i CommandCategory) String() string {
	if i < 0 || i+1 >= CommandCategory(len(_CommandCategory_index)) {
		return fmt.Sprintf("CommandCategory(%d)", i)
	}
	return _CommandCategory_name[_CommandCategory_index[i]:_CommandCategory_index[i+1]]
}
