// generated by stringer -output=interfaces_string.go -type=BorderType,CommandCategory,DockingType,KeyboardMode; DO NOT EDIT

package wicore

import "fmt"

const _BorderType_name = "BorderNoneBorderSingleBorderDouble"

var _BorderType_index = [...]uint8{0, 10, 22, 34}

func (i BorderType) String() string {
	if i < 0 || i+1 >= BorderType(len(_BorderType_index)) {
		return fmt.Sprintf("BorderType(%d)", i)
	}
	return _BorderType_name[_BorderType_index[i]:_BorderType_index[i+1]]
}

const _CommandCategory_name = "UnknownCategoryWindowCategoryCommandsCategoryEditorCategoryDebugCategory"

var _CommandCategory_index = [...]uint8{0, 15, 29, 45, 59, 72}

func (i CommandCategory) String() string {
	if i < 0 || i+1 >= CommandCategory(len(_CommandCategory_index)) {
		return fmt.Sprintf("CommandCategory(%d)", i)
	}
	return _CommandCategory_name[_CommandCategory_index[i]:_CommandCategory_index[i+1]]
}

const _DockingType_name = "DockingUnknownDockingFillDockingFloatingDockingLeftDockingRightDockingTopDockingBottom"

var _DockingType_index = [...]uint8{0, 14, 25, 40, 51, 63, 73, 86}

func (i DockingType) String() string {
	if i < 0 || i+1 >= DockingType(len(_DockingType_index)) {
		return fmt.Sprintf("DockingType(%d)", i)
	}
	return _DockingType_name[_DockingType_index[i]:_DockingType_index[i+1]]
}

const _KeyboardMode_name = "NormalInsertAllMode"

var _KeyboardMode_index = [...]uint8{0, 6, 12, 19}

func (i KeyboardMode) String() string {
	i -= 1
	if i < 0 || i+1 >= KeyboardMode(len(_KeyboardMode_index)) {
		return fmt.Sprintf("KeyboardMode(%d)", i+1)
	}
	return _KeyboardMode_name[_KeyboardMode_index[i]:_KeyboardMode_index[i+1]]
}
