// generated by stringer -output=key_string.go -type=KeyboardMode; DO NOT EDIT

package wicore

import "fmt"

const _KeyboardMode_name = "CommandModeEditModeAllMode"

var _KeyboardMode_index = [...]uint8{0, 11, 19, 26}

func (i KeyboardMode) String() string {
	i -= 1
	if i < 0 || i+1 >= KeyboardMode(len(_KeyboardMode_index)) {
		return fmt.Sprintf("KeyboardMode(%d)", i+1)
	}
	return _KeyboardMode_name[_KeyboardMode_index[i]:_KeyboardMode_index[i+1]]
}
