// Copyright 2014 Marc-Antoine Ruel. All rights reserved.
// Use of this source code is governed under the Apache License, Version 2.0
// that can be found in the LICENSE file.

// Generates editor/event_registry.go from wicore/events.go.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/parser"
	"go/token"
	"io/ioutil"
	"os"
	"sort"
	"strings"
	"text/template"

	"github.com/maruel/wi/tools/wi-event-generator/parse"
)

// TODO(maruel): Split the EventRegistry stub for plugin which forwards
// triggers, the host for the editor.

var tmplDecl = template.Must(template.New("render").Parse(`// generated by {{.CmdLine}}; DO NOT EDIT

package wicore

import (
	"io"

  "github.com/maruel/wi/wicore/key"
  "github.com/maruel/wi/wicore/lang"
)

// EventListener is to be used to cancel an event listener.
type EventListener interface {
	io.Closer
}

// NumberEvents is the number of known events.
const NumberEvents = {{len .Events}}

// EventTriggerRPC is the low level interface to propagate events to plugins.
type EventTriggerRPC interface {
	{{range .Events}}
	Trigger{{.Name}}RPC(packet Packet{{.Name}}, ignored *int) error{{end}}
}

// EventRegistry permits to register callbacks that are called on events.
//
// When the callback returns false, the next registered events are not called.
//
// Warning: This interface is automatically generated.
type EventRegistry interface {
	EventTrigger
	EventTriggerRPC

{{range .Events}}
	Register{{.Name}}(callback func({{.ParamsAsString}})) EventListener{{end}}
}

{{range .Events}}
// Packet{{.Name}} is for internal RPC use.
type Packet{{.Name}} struct {
{{range .ParamsUpperCase}}  {{.Name}} {{.Type}}
{{end}} }
{{end}}
`))

var tmplImpl = template.Must(template.New("render").Parse(`// generated by {{.CmdLine}}; DO NOT EDIT

package wicore

import (
  "errors"
	"log"
	"net/rpc"
  "sync"

  "github.com/maruel/wi/wicore/key"
  "github.com/maruel/wi/wicore/lang"
)
{{range .Events}}
type listener{{.Name}} struct{
	id       int
	callback func({{.ParamsAsString}})
}
{{end}}
// eventRegistry is automatically generated via wi-event-generator from the
// interface EventRegistry. It completely implements EventRegistry.
type eventRegistry struct {
  lock     sync.Mutex
  nextID   int
	deferred chan<- func()
{{range .Events}}
	{{.Lower}} []listener{{.Name}}{{end}}
}

// MakeEventRegistry returns an EventRegistry and the channel to read from to
// run the events piped in.
func MakeEventRegistry() (EventRegistry, chan func()) {
	// Reduce the odds of allocation within RegistryXXX() by using relatively
	// large buffers.
	c := make(chan func(), 2048)
	e := &eventRegistry{
		deferred: c,{{range .Events}}
		{{.Lower}}: make([]listener{{.Name}}, 0, 64),{{end}}
	}
	return e, c
}

func (er *eventRegistry) unregister(eventID int) {
  er.lock.Lock()
  defer er.lock.Unlock()
	// TODO(maruel): The buffers are never reallocated, so it's effectively a
	// memory leak.
	switch(eventID & {{.BitMask}}) { {{range .Events}}
	case {{.BitValue}}:
		for index, value := range er.{{.Lower}} {
			if value.id == eventID {
				copy(er.{{.Lower}}[index:], er.{{.Lower}}[index+1:])
				er.{{.Lower}} = er.{{.Lower}}[0 : len(er.{{.Lower}})-1]
				return
			}
		}{{end}}
  }
}{{range .Events}}

func (er *eventRegistry) Register{{.Name}}(callback func({{.ParamsAsString}})) EventListener {
  er.lock.Lock()
  defer er.lock.Unlock()
  i := er.nextID
  er.nextID++
  er.{{.Lower}} = append(er.{{.Lower}}, listener{{.Name}}{i, callback})
  return &eventListener{er, i | {{.BitValue}}}
}

func (er *eventRegistry) Trigger{{.Name}}({{.ParamsAsString}}) {
	er.deferred <- func() {
		items := func() []func({{.ParamsAsString}}) {
			er.lock.Lock()
			defer er.lock.Unlock()
			items := make([]func({{.ParamsAsString}}), 0, len(er.{{.Lower}}))
			for _, item := range er.{{.Lower}} {
				items = append(items, item.callback)
			}
			return items
		}()
		for _, item := range items {
			item({{.ParamsNames}})
		}
	}
}

func (er *eventRegistry) Trigger{{.Name}}RPC(packet Packet{{.Name}}, ignored *int) error {
	er.Trigger{{.Name}}({{.PacketParams}})
	return nil
}{{end}}

type unregister interface {
  unregister(id int)
}

type eventListener struct {
	unregister unregister
	id int
}

func (e *eventListener) Close() error {
	if e.id == 0 {
		return errors.New("EventListener already closed")
	}
	e.unregister.unregister(e.id)
	e.id = 0
	return nil
}

// RegisterPluginEvents registers all the events to be forwarded to the plugin
// through the interface EventTriggerRPC.
func RegisterPluginEvents(client *rpc.Client, e EventRegistry) EventListener {
	return multiCloser{ {{range .Events}}
		e.Register{{.Name}}(func({{.ParamsAsString}}) {
			packet := Packet{{.Name}} { {{.ParamsNames}} }
			out := 0
			if err := client.Call("EventTriggerRPC.Trigger{{.Name}}RPC", packet, &out); err != nil {
				log.Printf("RPC call failure: %s", err)
			}
		}),{{end}}
	}
}
`))

// Event describes one parsed event from the interface that will be used to
// generate the code.
type Event struct {
	Name            string
	Lower           string
	Index           int
	BitValue        string
	ParamsAsString  string      // "foo int, bar string"
	ParamsNames     string      // "foo, bar"
	Params          []parse.Arg // []Arg{{"foo", "int"}, {"bar", "string"}}
	ParamsUpperCase []parse.Arg // []Arg{{"Foo", "int"}, {"Bar", "string"}}
	PacketParams    string      // "packet.foo, packet.bar"
}

type tmplData struct {
	CmdLine string
	BitMask string
	Events  []Event
}

// Generation code.

func extractEvents(inputFile, inputType string, impl bool, bitmask uint) ([]Event, error) {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, inputFile, nil, 0)
	if err != nil {
		return nil, err
	}
	prefix := "Trigger"
	events := []Event{}
	inputT := parse.FindType(f, inputType)
	if inputT == nil {
		return nil, fmt.Errorf("failed to find type %s", inputType)
	}
	methods, err := parse.EnumInterface(inputT)
	if err != nil {
		return nil, err
	}
	methodNames := make([]string, len(methods))
	for i, m := range methods {
		methodNames[i] = m.Name
	}
	if !sort.StringsAreSorted(methodNames) {
		return nil, fmt.Errorf("methods of %s must be sorted by name", inputType)
	}
	for _, method := range methods {
		if !strings.HasPrefix(method.Name, prefix) {
			return nil, fmt.Errorf("method %s.%s doesn't have prefix %s", inputType, method.Name, prefix)
		}
		if len(method.Results) != 0 {
			return nil, fmt.Errorf("unexpected result on method %s.%s", inputType, method.Name)
		}
		name := method.Name[len(prefix):]
		lower := strings.ToLower(name[0:1]) + name[1:]
		names := make([]string, len(method.Params))
		full := make([]string, len(method.Params))
		paramsUpper := make([]parse.Arg, len(method.Params))
		packetParams := make([]string, len(method.Params))
		for i, arg := range method.Params {
			if len(arg.Name) == 0 {
				return nil, fmt.Errorf("argument %d must be named on method %s.%s", i, inputType, method.Name)
			}
			names[i] = arg.Name
			full[i] = fmt.Sprintf("%s %s", arg.Name, arg.Type)
			paramsUpper[i] = arg
			paramsUpper[i].Name = strings.ToUpper(paramsUpper[i].Name[0:1]) + paramsUpper[i].Name[1:]
			packetParams[i] = "packet." + paramsUpper[i].Name
		}
		// TODO(maruel): It creates an artificial limit of 2^23 event listener and
		// 2^8 event types on 32 bits systems.
		events = append(events, Event{
			Name:            name,
			Lower:           lower,
			Index:           len(events),
			BitValue:        fmt.Sprintf("0x%x", (len(events)+1)<<bitmask),
			ParamsAsString:  strings.Join(full, ", "),
			ParamsNames:     strings.Join(names, ", "),
			Params:          method.Params,
			ParamsUpperCase: paramsUpper,
			PacketParams:    strings.Join(packetParams, ", "),
		})
	}
	return events, nil
}

func generate(inputFile string, inputType string, impl bool) ([]byte, error) {
	// TODO(maruel): Make the bitmask seamless instead of hardcoded.
	bitmask := uint(24)
	events, err := extractEvents(inputFile, inputType, impl, bitmask)
	if err != nil {
		return nil, err
	}
	d := tmplData{
		// Skip os.Args[0] since it may point into $TMP.
		CmdLine: "go run ../tools/wi-event-generator/main.go " + strings.Join(os.Args[1:], " "),
		BitMask: fmt.Sprintf("0x%x", ((1<<32)-1)-((1<<bitmask)-1)),
		Events:  events,
	}
	out := bytes.Buffer{}
	tmpl := tmplDecl
	if impl {
		tmpl = tmplImpl
	}
	if err := tmpl.Execute(&out, d); err != nil {
		return nil, fmt.Errorf("failed to generate go code: %s", err)
	}
	return out.Bytes(), nil
}

func mainImpl() error {
	impl := flag.Bool("impl", false, "Generates the implementation, otherwise it generates the interface")
	outputFile := flag.String("output", "", "Output file")
	flag.Parse()

	if len(flag.Args()) != 0 {
		return fmt.Errorf("unexpected argument: %s", flag.Args())
	}
	if len(*outputFile) == 0 {
		return errors.New("-output is required")
	}
	src, err := generate("interfaces.go", "EventTrigger", *impl)
	if err != nil {
		return err
	}
	src, err = parse.FormatSource(src)
	err2 := ioutil.WriteFile(*outputFile, src, 0644)
	if err != nil {
		return err
	}
	return err2
}

func main() {
	if err := mainImpl(); err != nil {
		fmt.Fprintf(os.Stderr, "wi-event-generator: %s.\n", err)
		os.Exit(1)
	}
}
