// generated by stringer -type=Key; DO NOT EDIT

package key

import "fmt"

const _Key_name = "NoneEnterEscapeSpaceTabMetaF1F2F3F4F5F6F7F8F9F10F11F12F13F14F15BackspaceDeleteInsertHomeEndPageUpPageDownUpDownLeftRightlast"

var _Key_index = [...]uint8{0, 4, 9, 15, 20, 23, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 48, 51, 54, 57, 60, 63, 72, 78, 84, 88, 91, 97, 105, 107, 111, 115, 120, 124}

func (i Key) String() string {
	if i < 0 || i+1 >= Key(len(_Key_index)) {
		return fmt.Sprintf("Key(%d)", i)
	}
	return _Key_name[_Key_index[i]:_Key_index[i+1]]
}
