// generated by wi-event-generator; DO NOT EDIT

package editor

import (
	"errors"
	"sync"

	"github.com/maruel/wi/pkg/key"
	"github.com/maruel/wi/wicore"
)

type eventRegistry struct {
	lock   sync.Mutex
	nextID wicore.EventID

	documentCreated     map[wicore.EventID]func(a wicore.Document)
	documentCursorMoved map[wicore.EventID]func(a wicore.Document)
	terminalKeyPressed  map[wicore.EventID]func(a key.Press)
	terminalResized     map[wicore.EventID]func()
	viewCreated         map[wicore.EventID]func(a wicore.View)
	windowCreated       map[wicore.EventID]func(a wicore.Window)
	windowResized       map[wicore.EventID]func(a wicore.Window)
}

func (e *eventRegistry) Unregister(eventID wicore.EventID) error {
	e.lock.Lock()
	defer e.lock.Unlock()
	if _, ok := e.documentCreated[eventID]; ok {
		delete(e.documentCreated, eventID)
		return nil
	}
	if _, ok := e.documentCursorMoved[eventID]; ok {
		delete(e.documentCursorMoved, eventID)
		return nil
	}
	if _, ok := e.terminalKeyPressed[eventID]; ok {
		delete(e.terminalKeyPressed, eventID)
		return nil
	}
	if _, ok := e.terminalResized[eventID]; ok {
		delete(e.terminalResized, eventID)
		return nil
	}
	if _, ok := e.viewCreated[eventID]; ok {
		delete(e.viewCreated, eventID)
		return nil
	}
	if _, ok := e.windowCreated[eventID]; ok {
		delete(e.windowCreated, eventID)
		return nil
	}
	if _, ok := e.windowResized[eventID]; ok {
		delete(e.windowResized, eventID)
		return nil
	}
	return errors.New("trying to unregister an non existing event listener")
}

func (e *eventRegistry) RegisterDocumentCreated(callback func(a wicore.Document)) wicore.EventID {
	e.lock.Lock()
	defer e.lock.Unlock()
	i := e.nextID
	e.nextID++
	e.documentCreated[i] = callback
	return i
}

func (e *eventRegistry) onDocumentCreated(a wicore.Document) {
	items := func() []func(a wicore.Document) {
		e.lock.Lock()
		defer e.lock.Unlock()
		items := make([]func(a wicore.Document), 0, len(e.documentCreated))
		for _, c := range e.documentCreated {
			items = append(items, c)
		}
		return items
	}()
	for _, item := range items {
		item(a)
	}
}

func (e *eventRegistry) RegisterDocumentCursorMoved(callback func(a wicore.Document)) wicore.EventID {
	e.lock.Lock()
	defer e.lock.Unlock()
	i := e.nextID
	e.nextID++
	e.documentCursorMoved[i] = callback
	return i
}

func (e *eventRegistry) onDocumentCursorMoved(a wicore.Document) {
	items := func() []func(a wicore.Document) {
		e.lock.Lock()
		defer e.lock.Unlock()
		items := make([]func(a wicore.Document), 0, len(e.documentCursorMoved))
		for _, c := range e.documentCursorMoved {
			items = append(items, c)
		}
		return items
	}()
	for _, item := range items {
		item(a)
	}
}

func (e *eventRegistry) RegisterTerminalKeyPressed(callback func(a key.Press)) wicore.EventID {
	e.lock.Lock()
	defer e.lock.Unlock()
	i := e.nextID
	e.nextID++
	e.terminalKeyPressed[i] = callback
	return i
}

func (e *eventRegistry) onTerminalKeyPressed(a key.Press) {
	items := func() []func(a key.Press) {
		e.lock.Lock()
		defer e.lock.Unlock()
		items := make([]func(a key.Press), 0, len(e.terminalKeyPressed))
		for _, c := range e.terminalKeyPressed {
			items = append(items, c)
		}
		return items
	}()
	for _, item := range items {
		item(a)
	}
}

func (e *eventRegistry) RegisterTerminalResized(callback func()) wicore.EventID {
	e.lock.Lock()
	defer e.lock.Unlock()
	i := e.nextID
	e.nextID++
	e.terminalResized[i] = callback
	return i
}

func (e *eventRegistry) onTerminalResized() {
	items := func() []func() {
		e.lock.Lock()
		defer e.lock.Unlock()
		items := make([]func(), 0, len(e.terminalResized))
		for _, c := range e.terminalResized {
			items = append(items, c)
		}
		return items
	}()
	for _, item := range items {
		item()
	}
}

func (e *eventRegistry) RegisterViewCreated(callback func(a wicore.View)) wicore.EventID {
	e.lock.Lock()
	defer e.lock.Unlock()
	i := e.nextID
	e.nextID++
	e.viewCreated[i] = callback
	return i
}

func (e *eventRegistry) onViewCreated(a wicore.View) {
	items := func() []func(a wicore.View) {
		e.lock.Lock()
		defer e.lock.Unlock()
		items := make([]func(a wicore.View), 0, len(e.viewCreated))
		for _, c := range e.viewCreated {
			items = append(items, c)
		}
		return items
	}()
	for _, item := range items {
		item(a)
	}
}

func (e *eventRegistry) RegisterWindowCreated(callback func(a wicore.Window)) wicore.EventID {
	e.lock.Lock()
	defer e.lock.Unlock()
	i := e.nextID
	e.nextID++
	e.windowCreated[i] = callback
	return i
}

func (e *eventRegistry) onWindowCreated(a wicore.Window) {
	items := func() []func(a wicore.Window) {
		e.lock.Lock()
		defer e.lock.Unlock()
		items := make([]func(a wicore.Window), 0, len(e.windowCreated))
		for _, c := range e.windowCreated {
			items = append(items, c)
		}
		return items
	}()
	for _, item := range items {
		item(a)
	}
}

func (e *eventRegistry) RegisterWindowResized(callback func(a wicore.Window)) wicore.EventID {
	e.lock.Lock()
	defer e.lock.Unlock()
	i := e.nextID
	e.nextID++
	e.windowResized[i] = callback
	return i
}

func (e *eventRegistry) onWindowResized(a wicore.Window) {
	items := func() []func(a wicore.Window) {
		e.lock.Lock()
		defer e.lock.Unlock()
		items := make([]func(a wicore.Window), 0, len(e.windowResized))
		for _, c := range e.windowResized {
			items = append(items, c)
		}
		return items
	}()
	for _, item := range items {
		item(a)
	}
}
