// generated by go run ../tools/wi-event-generator/main.go ; DO NOT EDIT

package internal

import (
	"github.com/wi-ed/wi/wicore"
	"github.com/wi-ed/wi/wicore/key"
	"github.com/wi-ed/wi/wicore/lang"
)

// EventTriggerRPC is the low level interface to propagate events to plugins.
//
// It is implemented by wi/wicore/plugin, exported here to be used via RPC.
type EventTriggerRPC interface {
	TriggerCommandsRPC(packet PacketCommands, ignored *int) error
	TriggerDocumentCreatedRPC(packet PacketDocumentCreated, ignored *int) error
	TriggerDocumentCursorMovedRPC(packet PacketDocumentCursorMoved, ignored *int) error
	TriggerEditorKeyboardModeChangedRPC(packet PacketEditorKeyboardModeChanged, ignored *int) error
	TriggerEditorLanguageRPC(packet PacketEditorLanguage, ignored *int) error
	TriggerTerminalKeyPressedRPC(packet PacketTerminalKeyPressed, ignored *int) error
	TriggerTerminalMetaKeyPressedRPC(packet PacketTerminalMetaKeyPressed, ignored *int) error
	TriggerTerminalResizedRPC(packet PacketTerminalResized, ignored *int) error
	TriggerViewActivatedRPC(packet PacketViewActivated, ignored *int) error
	TriggerViewCreatedRPC(packet PacketViewCreated, ignored *int) error
	TriggerWindowCreatedRPC(packet PacketWindowCreated, ignored *int) error
	TriggerWindowResizedRPC(packet PacketWindowResized, ignored *int) error
}

// PacketCommands is exported for internal RPC use.
type PacketCommands struct {
	Cmds wicore.EnqueuedCommands
}

// PacketDocumentCreated is exported for internal RPC use.
type PacketDocumentCreated struct {
	Doc wicore.Document
}

// PacketDocumentCursorMoved is exported for internal RPC use.
type PacketDocumentCursorMoved struct {
	Doc wicore.Document
	Col int
	Row int
}

// PacketEditorKeyboardModeChanged is exported for internal RPC use.
type PacketEditorKeyboardModeChanged struct {
	Mode wicore.KeyboardMode
}

// PacketEditorLanguage is exported for internal RPC use.
type PacketEditorLanguage struct {
	L lang.Language
}

// PacketTerminalKeyPressed is exported for internal RPC use.
type PacketTerminalKeyPressed struct {
	K key.Press
}

// PacketTerminalMetaKeyPressed is exported for internal RPC use.
type PacketTerminalMetaKeyPressed struct {
	K key.Press
}

// PacketTerminalResized is exported for internal RPC use.
type PacketTerminalResized struct {
}

// PacketViewActivated is exported for internal RPC use.
type PacketViewActivated struct {
	View wicore.View
}

// PacketViewCreated is exported for internal RPC use.
type PacketViewCreated struct {
	View wicore.View
}

// PacketWindowCreated is exported for internal RPC use.
type PacketWindowCreated struct {
	Window wicore.Window
}

// PacketWindowResized is exported for internal RPC use.
type PacketWindowResized struct {
	Window wicore.Window
}
